class Customer {
  final String partyId;
  String name;
  String phone;
  String address;
  String tipn;
  String outstandingbalance;
  String email;
  String balanceType;
  String discountPer;
  String loyaltyPoint;
  String applyRewards;
  String partyGUID;
  String? city;
  String? zip;
  String? region;
  String? birthday;
  String? customerCode;
  String? nir;
  String? type;

  Customer({
    required this.partyId,
    required this.name,
    required this.phone,
    this.address = "",
    this.tipn = "",
    this.outstandingbalance = "0.00",
    this.email = "",
    this.balanceType = "CR",
    this.discountPer = "0",
    this.loyaltyPoint = "0",
    this.applyRewards = "No",
    this.partyGUID = "",
    this.city,
    this.zip,
    this.region,
    this.birthday,
    this.customerCode,
    this.nir,
    this.type,
  });

  factory Customer.fromJson(Map<String, dynamic> json) => Customer(
    partyId: json["partyID"] ?? "",
    name: json["title"] ?? "",
    phone: json["mobile"] ?? "",
    address: json["address"] ?? "",
    tipn: json["panNo"] ?? "",
    outstandingbalance: json["balance"] ?? "0.00",
    email: json["email"] ?? "",
    balanceType: json["balanceType"] ?? "",
    discountPer: json["discountPer"] ?? "0",
    loyaltyPoint: json["loyaltyPoint"] ?? "0",
    applyRewards: json["applyRewards"] ?? "No",
    partyGUID: json["PartyGUID"] ?? "",
  );

  Map<String, dynamic> toJson() => {
    "partyID": partyId,
    "title": name,
    "mobile": phone,
    "address": address,
    "panNo": tipn,
    "balance": outstandingbalance,
    "email": email,
    "balanceType": balanceType,
    "discountPer": discountPer,
    "loyaltyPoint": loyaltyPoint,
    "applyRewards": applyRewards,
    "partyGUID": partyGUID,
  };
}

final List<Customer> customers = <Customer>[
  Customer(
    partyId: "1",
    name: "John Doe",
    phone: "1234567890",
    address: "123 Main St, Anytown USA",
    tipn: "1234",
    outstandingbalance: "100.00",
    email: "john@example.com",
    balanceType: "CR",
    discountPer: "0",
    loyaltyPoint: "0",
    applyRewards: "No",
    partyGUID: "guid-1",
  ),
  Customer(
    partyId: "2",
    name: "Jane Doe",
    phone: "9876543210",
    address: "456 Elm St, Anytown USA",
    tipn: "5678",
    outstandingbalance: "50.00",
    email: "jane@example.com",
    balanceType: "CR",
    discountPer: "0",
    loyaltyPoint: "0",
    applyRewards: "No",
    partyGUID: "guid-2",
  ),
  Customer(
    partyId: "3",
    name: "Bob Smith",
    phone: "5555555555",
    address: "789 Oak St, Anytown USA",
    tipn: "9012",
    outstandingbalance: "75.00",
    email: "bob@example.com",
    balanceType: "CR",
    discountPer: "0",
    loyaltyPoint: "0",
    applyRewards: "No",
    partyGUID: "guid-3",
  ),
  Customer(
    partyId: "4",
    name: "Alice Johnson",
    phone: "1122334455",
    address: "101 Pine St, Springfield",
    tipn: "1122",
    outstandingbalance: "200.00",
    email: "alice@example.com",
    balanceType: "DR",
    discountPer: "5",
    loyaltyPoint: "10",
    applyRewards: "Yes",
    partyGUID: "guid-4",
  ),
  Customer(
    partyId: "5",
    name: "Charlie Brown",
    phone: "9988776655",
    address: "202 Birch Ave, Springfield",
    tipn: "9988",
    outstandingbalance: "150.00",
    email: "charlie@example.com",
    balanceType: "DR",
    discountPer: "0",
    loyaltyPoint: "5",
    applyRewards: "Yes",
    partyGUID: "guid-5",
  ),
  Customer(
    partyId: "6",
    name: "Diana Prince",
    phone: "1231231234",
    address: "303 Cedar Ln, Springfield",
    tipn: "1231",
    outstandingbalance: "300.00",
    email: "diana@example.com",
    balanceType: "DR",
    discountPer: "10",
    loyaltyPoint: "20",
    applyRewards: "Yes",
    partyGUID: "guid-6",
  ),
  Customer(
    partyId: "7",
    name: "Ethan Hunt",
    phone: "5566778899",
    address: "404 Maple Dr, Springfield",
    tipn: "5566",
    outstandingbalance: "75.00",
    email: "ethan@example.com",
    balanceType: "CR",
    discountPer: "0",
    loyaltyPoint: "3",
    applyRewards: "No",
    partyGUID: "guid-7",
  ),
  Customer(
    partyId: "8",
    name: "Fiona Gallagher",
    phone: "7788990011",
    address: "505 Oak Blvd, Springfield",
    tipn: "7788",
    outstandingbalance: "125.00",
    email: "fiona@example.com",
    balanceType: "CR",
    discountPer: "0",
    loyaltyPoint: "8",
    applyRewards: "Yes",
    partyGUID: "guid-8",
  ),
  Customer(
    partyId: "9",
    name: "George Costanza",
    phone: "9900112233",
    address: "606 Pine Ct, Springfield",
    tipn: "9900",
    outstandingbalance: "50.00",
    email: "george@example.com",
    balanceType: "CR",
    discountPer: "0",
    loyaltyPoint: "2",
    applyRewards: "No",
    partyGUID: "guid-9",
  ),
  Customer(
    partyId: "10",
    name: "Hannah Montana",
    phone: "1122334455",
    address: "707 Elm Way, Springfield",
    tipn: "1122",
    outstandingbalance: "175.00",
    email: "hannah@example.com",
    balanceType: "DR",
    discountPer: "5",
    loyaltyPoint: "12",
    applyRewards: "Yes",
    partyGUID: "guid-10",
  ),
  Customer(
    partyId: "11",
    name: "Ian Malcolm",
    phone: "2233445566",
    address: "808 Oak Ridge, Springfield",
    tipn: "2233",
    outstandingbalance: "225.00",
    email: "ian@example.com",
    balanceType: "DR",
    discountPer: "10",
    loyaltyPoint: "18",
    applyRewards: "Yes",
    partyGUID: "guid-11",
  ),
  Customer(
    partyId: "12",
    name: "Julia Roberts",
    phone: "3344556677",
    address: "909 Pine Hill, Springfield",
    tipn: "3344",
    outstandingbalance: "100.00",
    email: "julia@example.com",
    balanceType: "CR",
    discountPer: "0",
    loyaltyPoint: "6",
    applyRewards: "Yes",
    partyGUID: "guid-12",
  ),
  Customer(
    partyId: "13",
    name: "Kevin McCallister",
    phone: "4455667788",
    address: "1010 Maple Crest, Springfield",
    tipn: "4455",
    outstandingbalance: "300.00",
    email: "kevin@example.com",
    balanceType: "DR",
    discountPer: "15",
    loyaltyPoint: "25",
    applyRewards: "Yes",
    partyGUID: "guid-13",
  ),
  Customer(
    partyId: "14",
    name: "Lisa Simpson",
    phone: "5566778899",
    address: "1111 Oakwood, Springfield",
    tipn: "5566",
    outstandingbalance: "50.00",
    email: "lisa@example.com",
    balanceType: "CR",
    discountPer: "0",
    loyaltyPoint: "4",
    applyRewards: "No",
    partyGUID: "guid-14",
  ),
  Customer(
    partyId: "15",
    name: "Michael Scott",
    phone: "6677889900",
    address: "1212 Pine Valley, Springfield",
    tipn: "6677",
    outstandingbalance: "200.00",
    email: "michael@example.com",
    balanceType: "DR",
    discountPer: "5",
    loyaltyPoint: "15",
    applyRewards: "Yes",
    partyGUID: "guid-15",
  ),
  Customer(
    partyId: "16",
    name: "Nancy Drew",
    phone: "7788990011",
    address: "1313 Cedar Grove, Springfield",
    tipn: "7788",
    outstandingbalance: "125.00",
    email: "nancy@example.com",
    balanceType: "CR",
    discountPer: "0",
    loyaltyPoint: "7",
    applyRewards: "Yes",
    partyGUID: "guid-16",
  ),
  Customer(
    partyId: "17",
    name: "Oscar Martinez",
    phone: "8899001122",
    address: "1414 Oak Creek, Springfield",
    tipn: "8899",
    outstandingbalance: "75.00",
    email: "oscar@example.com",
    balanceType: "CR",
    discountPer: "0",
    loyaltyPoint: "3",
    applyRewards: "No",
    partyGUID: "guid-17",
  ),
  Customer(
    partyId: "18",
    name: "Pam Beesly",
    phone: "9900112233",
    address: "1515 Pine Ridge, Springfield",
    tipn: "9900",
    outstandingbalance: "150.00",
    email: "pam@example.com",
    balanceType: "CR",
    discountPer: "0",
    loyaltyPoint: "9",
    applyRewards: "Yes",
    partyGUID: "guid-18",
  ),
  Customer(
    partyId: "19",
    name: "Quentin Tarantino",
    phone: "1122334455",
    address: "1616 Oak Valley, Springfield",
    tipn: "1122",
    outstandingbalance: "250.00",
    email: "quentin@example.com",
    balanceType: "DR",
    discountPer: "10",
    loyaltyPoint: "20",
    applyRewards: "Yes",
    partyGUID: "guid-19",
  ),
  Customer(
    partyId: "20",
    name: "Rachel Green",
    phone: "2233445566",
    address: "1717 Pine Grove, Springfield",
    tipn: "2233",
    outstandingbalance: "100.00",
    email: "rachel@example.com",
    balanceType: "CR",
    discountPer: "0",
    loyaltyPoint: "5",
    applyRewards: "Yes",
    partyGUID: "guid-20",
  ),
];
